---
theme: jekyll-theme-minimal
title: Proxecto para o IES do Milladoiro
description: Páxina para presentar proxecto de dirección para o IES do Milladoiro
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
